### ISSUE TITLE
hetio.abbreviation.metaedges_from_metapath breaks for integers

### ISSUE THREAD

**Issue by gwaygenomics** [dhimmel/hetio#12]
I have been building hetnets for MSigDB at https://github.com/greenelab/interpret-compression and have been using MSigDB collection names for hetio metagraph IDs.

However, I am receiving an error in the function [`metapath_from_abbrev`](https://github.com/dhimmel/hetio/blob/62c4dd1db11733f9e50c980e38a0ccc483aa1546/hetio/hetnet.py#L329). For example, when calling `graph.metagraph.metapath_from_abbrev('GpC1')`

The traceback is:

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-2cbc2580bcf8> in <module>()
      1 DWPCs = collections.OrderedDict()
      2 for name, graph in hetnets.items():
----> 3     metapath = graph.metagraph.metapath_from_abbrev('GpC1')
      4     rows, cols, dwpc_matrix, seconds = dwpc(graph, metapath, damping=0.4)
      5     DWPCs[name] = dwpc_matrix

~/anaconda3/envs/interpret-compression/lib/python3.6/site-packages/hetio/hetnet.py in metapath_from_abbrev(self, abbrev)
    333         for metaedge_abbrev in metaedge_abbrevs:
    334             metaedge_id = hetio.abbreviation.metaedge_id_from_abbreviation(
--> 335                 self, metaedge_abbrev)
    336             metaedges.append(self.get_edge(metaedge_id))
    337         return self.get_metapath(tuple(metaedges))

~/anaconda3/envs/interpret-compression/lib/python3.6/site-packages/hetio/abbreviation.py in metaedge_id_from_abbreviation(metagraph, abbreviation)
    128     abbrev_to_kind = {v: k for k, v in metagraph.kind_to_abbrev.items()}
    129     source_kind = abbrev_to_kind[source_abbrev]
--> 130     target_kind = abbrev_to_kind[target_abbrev]
    131     metanode = metagraph.get_node(source_kind)
    132     for edge in metanode.edges:

KeyError: 'C'
```

It appears the root of the error is in in [line 332](https://github.com/dhimmel/hetio/blob/62c4dd1db11733f9e50c980e38a0ccc483aa1546/hetio/hetnet.py#L332) to the method `metaedges_from_metapath`:

```python
hetio.abbreviation.metaedges_from_metapath('GpC1')
>>> ['GpC']
```

Which also appears to break in line 114 in [`hetio/abbreviation.py`](https://github.com/dhimmel/hetio/blob/25628506efab232041740a4a2b1ab7ebcb821dbb/hetio/abbreviation.py#L114).

I have not looked in the specific line in too much detail but I was wondering if there would be a way to accept integers in metapath abbreviations.

```python
pattern = regex.compile('(?<=^|[a-z<>])[A-Z]+[a-z<>]+[A-Z]+')
```

**Comment by dhimmel** [comment]
Ah interesting case. You've identified the problematic line. The main difficulty is that we use case to determine what's an metanode (UPPER) and what's and edge (lower). Perhaps we could allow digits proceeding an initial letter to set the case? That would fix your issue and also allow G1Fp1C2, although the readability of such an abbreviation is poor.

**Comment by gwaygenomics** [comment]
Looks like this works for my use case (and others)

```python
>>> import regex
>>> pattern = regex.compile('(?<=^|[a-z<>])[A-Z0-9]+[a-z<>]+[A-Z0-9]+')
>>> pattern.findall('GiGpBP', overlapped=True)
['GiG', 'GpBP']
>>> pattern.findall('GpC1', overlapped=True)
['GpC1']
>>> pattern.findall('G1Fp1C2pC1', overlapped=True)
['G1Fp1C2', '1C2pC1']
```

Do you think this would introduce any unintended consequences? I can work around this issue by extracting metapaths by other means
