### ISSUE TITLE
CC licence isn't recommended for source code

### ISSUE THREAD

**Issue by einon** [dhimmel/hetio#3]
Would you consider changing it to something more usable, e.g. GPL as recommended by the CC?

[https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software)

**Comment by einon** [comment]
NM, CC0 is compatible with GPL

**Comment by dhimmel** [comment]
Hey @einon thanks for your interest.

As CC0 entirely waives copyright, there shouldn't be any incompatible licenses. Nevertheless, [CC0 is not an OSI-approved license](https://opensource.org/faq#cc-zero), although being the most open license. Therefore, in other repos we've [begun exploring](https://github.com/cognoma/cancer-data/issues/5) dual licensing where the repository can be used as CC0 or BSD 3-Clause. This is an option here if users would find that helpful.

@einon GPL is a rather restrictive license that creates incompatibilities and is difficult to comply with sometimes. Unless you strongly believe in copyleft licensing, you may want to consider a more permissive open source license such as BSD or MIT. Of course, it's up to you!
